name: Store
main: net.craftingstore.bukkit.CraftingStoreBukkit
version: 2.3.1
softdepend: [PlaceholderAPI]
api-version: "1.13"
commands:
  craftingstore:
    description: CraftingStore command
    aliases: [cs]
  csbuy:
    description: Buy command
    aliases: [buy]